### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Fibroblasto**
Clean up some unnecessary lines used  while writing the script.

### CODE REVIEW

**Comment by falense** [comment]
Hi!

I have merged the changes in the _fstab_ branch. Please look over them and see if it is as you intended.

https://github.com/sondree/b2_fuse/commits/fstab

Best

**Comment by falense** [comment]
Is your script dependent on the changes I made using the "-o" argument or anything else this branch https://github.com/sondree/b2_fuse/commits/fstab_branch ?

**Comment by Fibroblasto** [comment]
Sorry, I don't understand. The script doesnt have anything to do with fstab. It does't use the “mount” command at all. It is intended to be used in the master branch (and probably in other branches) such as it was when I uploaded the script.

The final output of the script is a command that might be something like:
exec python /home/Tom/b2_fuse/b2fuse.py --config_filename /home/Tom/b2_fuse/config_prueba2_bucket.yaml     /mnt/mnt

In the former example no additional options were set, but the additional options can be used.

**Comment by Fibroblasto** [comment]
In the script I made the possibility (not necessary) of setting in the config file that contain the connection parameters a line with the default mount point of that bucket. Might that interfere with the program now or in the future? That default mount point can be overridden when using the script

**Comment by Fibroblasto** [comment]
You concluded that b2fuse can not use fstab:

> I guess we can conclude then that it would be impossible to have B2Fuse work with fstab (as it does not pass along arguments to B2Fuse). Anyone wanting auto mount on boot should use one of the listed methods in the readme as recently contributed by @mattrummler.

Therefore, IMO the fstab branch should be discarded. As I told in a former comment, the script is to be used with the normal branch. If it is to be merged, it should be merged with either the master branch or with a new branch identical to the master.

Another thing: there is a problem in the file “permanent_mount.md” where you included the instructions of use of the bash script: It included angle quotes “<” and “>” it doesn't display properly; it looks like they are interpreted as code. For example, where I wrote “The configuration file mus be named "config_<bucket_name>_bucket.yaml"” now, what can be actually read is “The configuration file mus be named "config__bucket.yaml"”, which would make the script to fail (by the way, there's a typo of mine: I should have written “must” and not  “mus”). The same problem with other lines where  I used angled quores in the readme.

And one thing more: The script is intended to be used also in a non interactive way to mount the backet at startup, but to do that no more than 5 (perhaps 10) lines of code would have been enough, and it has 219 lines. Its main goal is to be a “stupid-proof” script that will allow any user to use b2fuse without learning how to use b2fuse.py. It may be invoked without arguments and it will ask all the options, included the bucket name and the mount point, or can be invoked with the bucket name or be invoked with the bucket name and the mount point. In all cases it will ask the user if any of the additional parameters should be added (--enable_hashfiles --use_disk --temp_folder).

**Comment by falense** [comment]
There are two branches relating to fstab use (sorry for the poor naming convention):

The "fstab branch" with the "-o" changes that did not work.  I have discarded this branch.

The other "fstab" branch which is just a staging branch before merging things to master. I do not maintain multiple separate branches. In other words, it is just there so that you can review the changes before I potentially merge them.

I found a way to make the &lt; and &gt; show up properly and I have merged with master. As such, we can close this pull request.

Best 
Sondre

**Pull request merged**
